name: Build and Release for Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true

jobs:
  build:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  # 使用更新的 Go 版本

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -u github.com/PuerkitoBio/goquery

    - name: Build
      run: |
        go build -v -o scilla ./cmd/scilla

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_tag || github.ref }}
        release_name: Release ${{ github.event.inputs.release_tag || github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./scilla
        asset_name: scilla-linux-amd64
        asset_content_type: application/octet-stream
